### ISSUE TITLE
Albo tab albo spacje

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#13]
Do zagnieżdźania używaj zawsze tego samego a nie w jednym miejscach TAB a w innych spacji, bo kod będzie źle sformatowany (np. końcówka funkcji `wykonaj_naj_ruch`).

**Comment by michal2409** [comment]
akurat to github dziwnie formatuje (podobnie jest w koncowce maina), w jak sie pobierze plik to powinno byc normalnie.

**Comment by wlodekf** [comment]
Nie to nie jest wina githuba tylko edytora, który używasz albo sposobu w jaki robisz wcięcia. Zawsze używaj TAB.
