### ISSUE TITLE
Stałe

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#16]
Stałe w kodzie programu należy zastąpić przez odpowiednie const tak aby w razie potrzeby zmiany danej wartości nie trzeba było szukać w programie wszystkich miejsc gdzie dana wartość występuje. 
Tutaj na pewno taką stałą/stałymi są wymiary planszy 8x8.

**Comment by wlodekf** [comment]
Wydaje mi się, że w C stałe raczej definiuje się przy pomocy #define tak jak masz dla WIERSZE i KOLUMNY a nie const (napisałem w skrócie). 
Stałe aby się wyróżniały pisze się dużymi literami.

**Comment by wlodekf** [comment]
Nie z dużej litery tylko DUŻYMI LITERAMI.

**Comment by wlodekf** [comment]
Nazwij te stałe WIERSZE, KOLUMNY, a maksymalną liczbę linii wejściowych MAX_LINII

**Comment by michal2409** [comment]
stała MAX_LINII jest potrzebna ? Nigdzie poza tamtym kodem nie pisze o tym

**Comment by wlodekf** [comment]
Też mi się wydaje, że to ograniczenie jest niepotrzebne, czyta się do końca wejścia.
