### ISSUE TITLE
Kiepskie nazwy zmiennych

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#19]
W funkcji `graj` masz kiepską nazwę dla zmiennej `wczytaj`. Czasowniki raczej stosuje się dla nazw funkcji a nie dla zmiennych przechowujących dane. Powinno raczej być `wczytane` albo `dane` albo `linia`.

Po za tym, korzystając z fgets masz dwa wskaźniki do bufora. Używaj jednego a nie raz jeden a za chwilę drugi to wprowadza niepotrzebne zamieszanie.

Tak samo nazwa `rownosc` jest kiepska, powinno być 'brak_ruchu', 'pass', czy coś w tym stylu a nie nazwa od znaku, przy pomocy, którego reprezentuje się ten stan. A tak w ogóle to ona nie jest potrzebna.

Podobnie jest ze zmienną `pytajnik`, kiepska nazwa a oprócz tego w ogóle ta zmienna nie jest potrzebna. Zobacz jak/gdzie jest używana i zobaczysz, że można się bez niej spokojnie obyć.

**Comment by michal2409** [comment]
Da sie obejsc bez zmiennej wczytane ? Teraz musze robic wczyt_wiersz[4] jak daje mniej to zle wtedy czyta.

**Comment by wlodekf** [comment]
Nie wiem czy da się obejść bez niej to zależy jak działa funkcja fgets, czy będziesz miał możliwość sprawdzenia czy linia nie jest pusta/nie ma końca pliku. Ona może być ale używaj jej tylko do sprawdzenia czy nie jest NULL, do czytania znaków używaj bufora.

wczyt_wiersz może mieć więcej znaków, nawet tak jak miał 80 to nie ma specjalnie znaczenia.

wczyt_wiersz[3] nie działa? Chyba pod windows bo tam koniec linii to dwa znaki. Daj trochę więcej.

W tej funkcji zmień nazwy nie nazywaj zmianych "*wiersz*" bo to się nakłada/kłóci z wierszami w planszy. Używaj raczej "linia", nr_linii, linia, itp.

**Comment by michal2409** [comment]
w tej funkcji zmienne wiersz, kolumna odpowiadaja wlasnie za wspolrzedne granego ruchu wiec nazwanie wiersza nr_linii bedzie mylace bo nie bedzie wiadomo czy chodzi o linie pionowa czy pozioma

**Comment by wlodekf** [comment]
Chodziło mi od dl_wier, nr_wier, wczyt_wiersz (nie o wiersz i kolumna)
