### ISSUE TITLE
Używanie niesprawdzonych danych

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#20]
W funkcji `graj` wpuszczasz w system/program niesprawdzone dane. W przypadku gdy na wejściu są dwa znaki nie robisz sprawdzenia czy są poprawne a wpuszczasz je w `wykonaj_ruch`. To jest niebezpieczne, w ten sposób powstają dziury w systemach. Na szczęście w tym przypadku później masz sprawdzenie czy wiersz lub kolumna nie jest poza zakresem ale nie było daleko abyś czytał poza planszą.
Sprawdzenie poprawności należy zrobić jak najwcześniej i od razu reagować.

**Comment by michal2409** [comment]
Jak robie sprawdzenie przy wczytywaniu to lepiej zostawic czy usunac tamto w wykonaj ruch ?

**Comment by wlodekf** [comment]
Niech zostanie, sprawdzeń nigdy za dużo
