### ISSUE TITLE
Rozmiar danych wejściowych

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#25]
Z czego wynikają te wartości stałych dla danych wejściowych? W specyfikacji nie ma nic na ten temat.
Ograniczenie, że linia ma max 80 znaków nic nie daje, nie jest w niczym lepsze niż ograniczenie do powiedzmy 3 znaków + koniec linii.
Jeżeli są 3 znaki to dane są niepoprawne. A to, że możesz wczytać 80 nic nie daje, bo zawsze na wejściu możesz dostać 150 znaków w linii.

A ograniczenie na 100 wierszy, do czego jest potrzebne?

Stałe WIERSZE, KOLUMNY lepiej wykorzystać do określenia rozmiaru planszy.

**Comment by michal2409** [comment]
to bylo skopiowane z tego kodu do wczytania co byl na poczatku
![zrzut ekranu 2017-11-23 o 16 12 04](https://user-images.githubusercontent.com/14821051/33179277-2009471c-d069-11e7-8d62-e090b4bbb357.png)
