### ISSUE TITLE
Niejasny kod

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#29]
Ten kawałek kodu jest niejasny. Po pierwsze zmieniłbym nazwę brak_legal na brak_ruchu.
Dodałbym też komentarz, który wyjaśnia co tu się dzieje bo chwilę na to patrzyłem i do końca nie wiem o co dokładnie chodzi.

```
brak_legal = wygeneruj_naj_ruch(plansza, 'C', 0);
if(!brak_legal)
     printf("= ");
koniec_gry = wygeneruj_naj_ruch(plansza, 'B', 1) * brak_legal;
```

**Comment by michal2409** [comment]
czy po dodaniu komentarza dalej jest nie jasne ?
