### ISSUE TITLE
Optymalizacja - operacje na planszy

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#30]
Masz 3 funkcje, które robią bardzo podobne rzeczy, tzn. przechodzą po całej planszy i coś tam robią na każdym polu. Można by je połączyć w jedną funkcję (np. `operacja_na_planszy`), dodając parametr, który by mówił co ma być zrobione (jaka operacja wykonana) a w środku w pętli i na końcu dodać switch, który by wykonywał odpowiednią akcję.

**Comment by michal2409** [comment]
terez jak zmienilem z int na bool to dwie z tych funkcji zwraca inta a jedna bool, mozna polaczyc te dwie co zwraca inta bo w wykonaj ruch nie chodzimy po planszy bezposrednio, tylko za pomoca odwolania do licz_zdobyte_pionki

**Comment by wlodekf** [comment]
chodzi o inicjalizuj_plansze, rysuj i wypisz_stan

**Comment by michal2409** [comment]
dosyc brzydko to wyglada, linijek nie zyskujemy a wydaje sie mniej czytelne

**Comment by wlodekf** [comment]
jak uważasz, wydaje mi się, że z 10 linijek można zyskać, ale to nie konkurs na najkrótszy program
