### ISSUE TITLE
Brak ruchu

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#34]
Zmienna brak_ruchu w wygeneruj_ruch nie jest ci potrzebna. Kiedy jest brak ruchu? Gdy max_zamian == 0 więc ten warunek możesz zwrócić.

**Comment by wlodekf** [comment]
Zle to zapisałeś, warunek powinien być odwrotny, zresztą sprawdź na danych testowych

**Comment by michal2409** [comment]
na testowych dziala

**Comment by wlodekf** [comment]
ok, widzę, że zmieniłeś wartość zwracaną przez funkcję na przeciwną, teraz zwraca true gdy jest ruch
