### ISSUE TITLE
Dziwny kod

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#35]
Ta konstrukcja na końcu graj() jest dziwna
```
if (feof(stdin)) {
     dl_linii ++;
}
```
postaraj się tak zrobić aby to nie było potrzebne.

**Comment by michal2409** [comment]
wlasnie getline jak czyta ostatnia linie to nie dodaje do dlugosci linii znaku konca pliku przez co jak pozniej zmniejsze dlugosc o 1 to sie psuje

**Comment by michal2409** [comment]
moge ew sprawdzac czy na koncu wczytanej linii jest znak konca linii, wtedy bedzie czytelniej

**Comment by wlodekf** [comment]
Nie rozumiem, opisz jak to działa. Która linia jest ostatnia? Co/jaka długość jest zwracana dla normalnych linii (zakończonych \n) a jaka dla ostatniej? Zwraca coś jeszcze po ostatniej linii zakończonej \n ?

**Comment by michal2409** [comment]
To jednak nie jest potrzebne, no jest napisane "Wolno założyć, że każde polecenie użytkownika, także ostatnie, jest w wierszu poprawnie zakończonym reprezentacją końca wiersza \n."
