### ISSUE TITLE
Błąd kompilacji

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#37]
U mnie pod linuxem się nie kompiluje

nazwa.c: In function ‘graj’:
nazwa.c:146:13: error: implicit declaration of function ‘getline’ [-Werror=implicit-function-declaration]
  dl_linii = getline(&linia, &dl, stdin);
             ^
cc1: all warnings being treated as errors

**Comment by michal2409** [comment]
jak kompiluje przez ssh na mimowych kompach to tez jest ten blad

**Comment by michal2409** [comment]
juz powinno dzialac
