### ISSUE TITLE
Koniec gry

### ISSUE THREAD

**Issue by michal2409** [michal2409/Reversi#39]
"Program czyta z wejścia i wykonuje wszystkie polecenia użytkownika. Nie przerywa pracy przed dojściem do końca danych nawet, gdyby stwierdził, że dalsza gra nie ma sensu." rozumiesz to tak, ze nawet jak jest teoretycznie koniec gry np. brak ruchu to i tak czytam dalej ruchy i je wyswietlam ?

**Comment by wlodekf** [comment]
Na to wygląda, wyświetlamy znaki zapytania
