### ISSUE TITLE
Czytanie linii przy pomocy getline

### ISSUE THREAD

**Issue by wlodekf** [michal2409/Reversi#40]
Tutaj na końcu masz przykład jak to powinno się zapisać aby nie było dwóch wywołań
http://man7.org/linux/man-pages/man3/getline.3.html

Jaka powinna być / jaka będzie reakcja programu na przypadek gdy w środku będzie linia pusta (tylko newline, dlugość == 0)?

**Comment by michal2409** [comment]
wydaje mi sie ze "?", jeszcze dopytam

**Comment by michal2409** [comment]
potwierdzilem ze reakcja powinna byc jak na zle wejscie
